version: '3.8'
services:
  app:
    image: golang:1.16
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    restart: unless-stopped
    networks:
      kool_global:
        aliases:
          - api_mocker_dev

networks:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
